### ISSUE TITLE
Question: instantiating pg-range with the pg Pool object

### ISSUE THREAD

**Issue by shaunhurley** [WhoopInc/node-pg-range#11]
Hi,

Appreciate your efforts, am successfully using the "var Range = require("pg-range").Range;" approach in order to create and inject ranges into a pg database.

I've not been able to install into pg when using the "const { Pool } = require('pg')" pattern instead of the var pg = require("pg") in order to call "require("pg-range").install(pg);" and query ranges  i.e. 

const { Pool } = require('pg');
require("pg-range").install(Pool);

gives "Cannot read property 'getTypeParser' of undefined"

Thanks!

Shaun

**Comment by benesch** [comment]
Yeah, you're destructuring away the object that pg-range needs access to in order to install itself. Try this:

```js
const pg = require('pg');
const { Pool } = pg;
require('pg-range').install(pg);
```

**Comment by shaunhurley** [comment]
Yeah, that makes sense,, and it works - perfect, thanks!

**Comment by benesch** [comment]
You're welcome!
