### ISSUE TITLE
Missing strange API on Range type 

### ISSUE THREAD

**Issue by htulipe** [WhoopInc/node-pg-range#13]
If one only install "pg-range", the `Range` type will only have a `toPostgres` method exposed while actually there is all the methods from "strange" (begin, end, ...). They are just not made visible to TS.

This is fixable by also installing typings: `yarn add -W @types/strange`.

Cleaner fix: pg-range should declare a dependency to @types/strange

Cheers

**Comment by bdbaraban** [comment]
I've put up a PR (#14) to do just this.

**Comment by benesch** [comment]
Fixed in #14. Thanks @bdbaraban!
