### ISSUE TITLE
Very similar to stRange.js. Maybe use stRange.js internally?

### ISSUE THREAD

**Issue by moll** [WhoopInc/node-pg-range#3]
Hey,

I created [stRange.js](https://github.com/moll/js-strange) a while back for much the same purpose. It isn't directed at node-pg, so it requires a manual `PgTypes.setTypeParser` to have it parse the types. It does, however, support more operations, comes with a simple interval tree implementation, is fully documented etc. Perhaps your PgRange can just return stRange instances instead of rewriting all that. ;-)

Cheers

**Comment by benesch** [comment]
Amazing! I looked for something exactly your library back when I started this project; don't know how I missed it. Glad you tracked me down instead.

I'll add this to my queue.

**Comment by benesch** [comment]
@moll unfortunately, as I understand it, the AGPL would require source code to be made available if stRange.js is used over a network, which is far more restrictive than this package's MIT license. Closing for now; let me know if you change the license.

**Comment by waisbrot** [comment]
MIT is such a pointless license.

**Comment by benesch** [comment]
You'd prefer the GPL?

**Comment by waisbrot** [comment]
Mostly I'm just hassling you because I feel nostalgic when you do a wave of PRs.

But in general I think it's sad that FOSS has been twisted into more free shit for corporations.You (benesch) might have enough good stuff out there that it gets you some name-recognition and makes getting a job easier. And you'd want a very permissive license if you're going to leverage a massive success into a freemium consulting business or something. 

But for the stuff in the middle, I dislike MIT (and BSD and Apache, etc) because they talk about attribution and you're not actually going to get that. I think public domain is a more honest license for everyone who likes MIT.

I think that the GPL is brave (and the AGPL is braver) for the way that they fight for freedom. They seem to be losing the battle, though.

**Comment by moll** [comment]
While I agree with @waisbrot that MITs et alii are to software what leeching is to P2P, stRange.js is actually *Lesser* AGPL, which in summary allows/requires the following. ;)
- You can use this program for no cost.
- You can use this program for both personal and commercial reasons.
- You do not have to share your own program's code which uses this program.
- You have to share modifications (e.g bug-fixes) you've made to this program.

https://github.com/moll/js-strange/blob/master/LICENSE

**Comment by waisbrot** [comment]
I'd seen that in your LICENSE file, but I couldn't find such a thing on the Gnu site (and they've deprecated the LGPL). Is the 

> Additional permission under the GNU Affero GPL version 3 section 7:
If you modify this Program, or any covered work, by linking or
combining it with other code, such other code is not for that reason
alone subject to any of the requirements of the GNU Affero GPL version 3.

clause in your license your own addition, or did you get it from somewhere authoritative?

**Comment by moll** [comment]
LGPL deprecated? Seems alive and well on https://www.gnu.org/licenses/licenses.html, though.

Given that I own the copyright for code I've written, I am the authoritative source for licensing. ^_^ It's basically in the same spirit as LGPL, but with that running-on-server loophole fixed by AGPL. I wish there were an OSI sanctioned Lesser AGPL available, but there isn't, so we'll have to make due with an permission addition. That's why I added the human-readable list — to convey my desires sans legalese.

I am open for licensing suggestions as long as those 4 tenets remain. I presume we agree on those. :)

**Comment by waisbrot** [comment]
I'm referring to ["Why you shouldn't use the Lesser GPL for your next library"](https://www.gnu.org/licenses/why-not-lgpl.html). Is your argument that a library for parsing ranges is not unique enough to fall under the Readline example and would be more like libc? I'm just curious.

Anyway, @benesch I agree with @moll that the stRange.js license is compatible with node-pg-range and I think it would be worth considering that LAGPL license as a drop-in replacement for the MIT.

**Comment by benesch** [comment]
Works for me! See PR.
